### ISSUE TITLE
Mokuro not using GPU even after following steps from issue 21. 

### ISSUE THREAD

**Issue by Paramestus** [kha-white/mokuro#101]
I'm trying to use Mokuro OCR with GPU
I installed Cuda 118, cuda 125, (Like several attempts with different ones)
pytorch as instructed (Used both Pytorch 11.8 and 12.1 as shown here https://pytorch.org/get-started/locally/) 
import torch
print(torch.__version__)
print(torch.cuda.is_available())
shows as TRUE
I also made sure that the environment path variables were correct.

Python> also tried with 3.9 and now 3.10.10
My GPU is a RTX 3050 6gb VRAM laptop. 

![Screenshot 2024-06-29 080636](https://github.com/kha-white/mokuro/assets/174206771/6d27b2aa-fbdb-4343-a0fd-58d765a5941a)
It just keeps using 100%CPU (Pic here https://imgur.com/phGM4Hs ) and even goes below 40% CPU, unusable... Please help.

**Comment by Kanjirito** [comment]
Sadly I don't have a GPU that can use CUDA so I can't actually test this but I believe that the issue is that the text detection part is hardcoded to use the CPU. [Here is the relevant line](https://github.com/kha-white/mokuro/blob/master/mokuro/manga_page_ocr.py#L37C117-L37C129). If you change `device='cpu'` to `device='cuda'` it should start using your GPU. I'm not sure why it is this way so maybe it will cause issues but it's worth a try if you are willing to manually edit your installed version.

**Comment by Paramestus** [comment]
> Sadly I don't have a GPU that can use CUDA so I can't actually test this but I believe that the issue is that the text detection part is hardcoded to use the CPU. [Here is the relevant line](https://github.com/kha-white/mokuro/blob/master/mokuro/manga_page_ocr.py#L37C117-L37C129). If you change `device='cpu'` to `device='cuda'` it should start using your GPU. I'm not sure why it is this way so maybe it will cause issues but it's worth a try if you are willing to manually edit your installed version.

This is weird, it keeps using the CPU but now is way faster, at least now it's usable, thank you very much.

**Comment by TheTabbingman** [comment]
Just FYI in order to see cuda GPU usage in task manager. You have to change the graph to show cuda by click on the graph title, and changing it to cuda.

**Comment by kha-white** [comment]
Text detector should now use CUDA if available in mokuro>=0.2.1
