### ISSUE TITLE
Can't move processed manga to other computers

### ISSUE THREAD

**Issue by KolbyML** [kha-white/mokuro#20]
I copied the ocr folder and the html file but when I tried to open it on another machine it didn't work. Is there a solution to make the process manga portable not including turning it into a pdf

**Comment by YashaNoos** [comment]
You don't need the ocr folder to make it work, but you'll need the folder containing the manga's image file in the same place as the HTML.

**Comment by NolanGames3** [comment]
I had the same issue trying to move it to a phone/tablet too.

**Comment by Doubledealer** [comment]
Mokuro html's work on the computer, but I too have the same issue when copying to phone. Tried copying it to my android phone (image folder, ocr folder, and html's. i.e. same folder structure as what I had on my windows computer) and the html just opens up blank, no images. Copying these same files back onto my computer and the files still work so the files themselves don't seem to be modified in any way when they're being copied across from computer to phone. Rather, the problem seems to be somehow a lack of read access to the image files on the phone? (Even though I'm pretty sure I've given my browser all the necessary permissions and the file properties say the images are readable)

![image](https://user-images.githubusercontent.com/34986412/222885880-88cbe6f7-d6f0-4e01-9240-eafb2eb59177.png)
_No images are loading, but OCR text is still present. Screenshot of opening up the html on phone through computer. It looks the same when I directly open up the html on the phone._
