### ISSUE TITLE
Mokuro html only lets me hover panels for a japanese to english 'word' translation

### ISSUE THREAD

**Issue by onxeyedkxng** [kha-white/mokuro#40]
Mine looks different to the video

Instead of like the demo video on github giving the full translation and meaning with the japanese I only get an exact english word translation when i hover the mouse over the japanese text. And I had to turn google translate on for this.

Also, when I go 'right click', 'inspect', 'console' i get three translation errors for coding 

This is what the error says

Failed to load resource: net::ERR_FILE_NOT_FOUND
file://translate.google.com/gen204?sl=auto&tl=en&textlen=119&ttt=540&ttl=256&ttf=598&sr=1&nca=te_time&client=te_lib&logld=vTE_20221207

Did anyone get something similar?

Apparently yomichan is also good but I really ceebs learning to code another html text translator again https://rentry.co/lazyXel#mangaocr-or-manga-with-yomichan

It seems like this error is from mokuro's end

**Comment by Ceynou** [comment]
But that has nothing to do with mokuro, it only provides selectable text, or am I getting your issue wrong?

Also yomichan isn't just "also good" there's literally nothing better

**Comment by ChristopherFritz** [comment]
Adding to what Ceynou wrote, Mokuro solves only one part of the process: Taking the output of OCR and overlaying it on top of the source manga pages (as well as adding navigation between pages).

In order to make use of the OCR output, you still need an extension such as the free Yomichan or subscription-based Migaku, along with an installed dictionary, to get the desired results.  The demonstration video clip appears to use Yomichan with the JMDict dictionary installed.

Google Translate isn't needed, and will probably only get in the way.

Recommendation: Install [Yomichan](https://foosoft.net/projects/yomichan/) and the "jmdict_english.zip" dictionary file, and follow the steps on the Yomichan website on how to use the extension.

**Comment by onxeyedkxng** [comment]
I found Mokuro pretty difficult to install.

What's the easiest way to download yomichan and JMDict? Maybe there's a simple step by step guide for both?

**Comment by onxeyedkxng** [comment]
Okay I downloaded Yomichan with dictionaries but it still doesn't work in my html manga I created with Mokuro any ideas?

**Comment by ChristopherFritz** [comment]
It's possible Yomichan cannot access local files (file: protocol), for security purposes.

If you are on Chrome (or a Chromium-based browser), you need to enable support for it in Yomichan's extension settings.  The setting is called "Allow access to file URLs".

**Comment by onxeyedkxng** [comment]
Got it working bro cheers much thanks
